services:
  tt-bot:
    build: .
    image: ghcr.io/karilaa-dev/tt-bot:latest
    env_file:
      - .env
    # volumes:
    # - ./cookies.txt:/app/cookies.txt
    # - ./proxies.txt:/app/proxies.txt:ro
    restart: unless-stopped
    depends_on:
      - db

  stats-bot:
    build:
      context: .
      dockerfile: Dockerfile.stats
    image: ghcr.io/karilaa-dev/tt-bot-stats:latest
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db

  telegram-bot-api:
      image: aiogram/telegram-bot-api:latest
      volumes:
        - telegram-bot-api-data:/var/lib/telegram-bot-api
      env_file:
      - .env
      restart: unless-stopped

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-ttbot-db}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  telegram-bot-api-data:
  pgdata:
